apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: fgc
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: udp
      port: 6831
      targetPort: 6831
      protocol: UDP
  type: ClusterIP
